### ISSUE TITLE
问三个小问题？

### ISSUE THREAD

**Issue by didiaohu** [ProtoTeam/blog#4]
1、请问下有没有用 "mvc 构建一个模块的demo"     2、请问下有没有 "容器型组件与展示型组件的demo"   3、请问下有没有 "跨模块通信的demo "

**Comment by panyifei** [comment]
目前还没有demo，我们内部孵化的架构KOP还没有准备好对外输出，补齐demo和文档之后很快会开放出来

**Comment by didiaohu** [comment]
好的，谢谢，具体什么时候会开放出来呢，非常着急等待您这边的demo
